version: '2'
services:
    customdatatypes-app:
        image: customdatatypes
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://customdatatypes-postgresql:5432/customdatatypes
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=customdatatypes-elasticsearch:9300
        ports:
            - 8080:8080
    customdatatypes-postgresql:
        extends:
            file: postgresql.yml
            service: customdatatypes-postgresql
    customdatatypes-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: customdatatypes-elasticsearch
